version: '3.8'

services:
  # Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  # Backend (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - DATABASE_URL=sqlite:///./data/nyay_sarthi.db
      - CHROMA_PERSIST_DIRECTORY=/app/vector_db
      - UPLOAD_DIR=/app/uploads
      - LOG_DIR=/app/logs
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./vector_db:/app/vector_db
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - redis
      - chroma

  # Vector Database (Chroma)
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8001:8000"
    environment:
      - CHROMA_SERVER_AUTHN_CREDENTIALS_FILE=/chroma/server.htpasswd
      - CHROMA_SERVER_AUTHN_PROVIDER=chromadb.auth.basic.BasicAuthServerProvider
    volumes:
      - ./vector_db:/chroma/chroma
      - ./chroma/server.htpasswd:/chroma/server.htpasswd

  # Redis (for background jobs)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Nginx (reverse proxy, optional for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    profiles:
      - production

volumes:
  redis_data:

networks:
  default:
    name: nyay-sarthi-network